creation_rules:
  - path_regex: enc.env
    key_groups:
      - age:
          - age1alwl6u2ypueddmkquuhpxtfx4u7rwdgttnre4y64ku4erp6pue2sqlravx # Alex CK
          - age1dncrgzyafvwjwdh8apz2j85kscmy0dvr4eh922aqm4fnn35dxqjslyqwk9 # Deployment Key
  - path_regex: ^config-sops/.*\.ya?ml$
    encrypted_regex: '^(token)$'
    key_groups:
      - age:
          - age1alwl6u2ypueddmkquuhpxtfx4u7rwdgttnre4y64ku4erp6pue2sqlravx # Alex CK
          - age1dncrgzyafvwjwdh8apz2j85kscmy0dvr4eh922aqm4fnn35dxqjslyqwk9 # Deployment Key