services:
  gatus:
    image: twinproduction/gatus:v5.24.3
    restart: always
    ports:
      - "8080:8080"
    environment:
      - GATUS_CONFIG_PATH=/config
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./config:/config
    networks:
      - web
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - web

volumes:
  pgdata:

networks:
  web: