defaults-openstack: &defaults_openstack
  group: OpenStack
  interval: 5m
  ui:
    hide-hostname: true
    hide-port: true
    hide-conditions: true
    hide-url: true
  conditions:
    - "[STATUS] == any(200, 401, 400, 300)"

endpoints:
  - name: OpenStack Web UI (Horizon)
    url: "https://openstack.stfc.ac.uk"
    <<: *defaults_openstack
    ui:
      hide-hostname: false
      hide-port: false
      hide-url: false
    conditions:
      - "[STATUS] == 200"

  - name: OpenStack Identity (Keystone)
    url: "https://openstack.stfc.ac.uk:5000"
    <<: *defaults_openstack

  - name: OpenStack Identity v3 (Keystone v3)
    url: "https://openstack.stfc.ac.uk:5000/v3"
    <<: *defaults_openstack

  - name: OpenStack Compute (Nova)
    url: "https://openstack.stfc.ac.uk:8774/v2.1"
    <<: *defaults_openstack

  - name: OpenStack Legacy Compute (Nova Legacy)
    url: "https://openstack.stfc.ac.uk:8774/v2"
    <<: *defaults_openstack

  # Disabled: Un-used
  # - name: OpenStack EC2 API
  #   url: "https://openstack.stfc.ac.uk:8788/v2/"
  #   <<: *defaults_openstack

  - name: OpenStack Network (Neutron)
    url: "https://openstack.stfc.ac.uk:9696"
    <<: *defaults_openstack

  - name: OpenStack Load Balancer (Octavia)
    url: "https://openstack.stfc.ac.uk:9876"
    <<: *defaults_openstack

  - name: OpenStack Volume (Cinder v3)
    url: "https://openstack.stfc.ac.uk:8776/v3"
    <<: *defaults_openstack

  - name: OpenStack Object Store (Swift)
    url: "https://s3.echo.stfc.ac.uk/swift/healthcheck"
    <<: *defaults_openstack

  - name: OpenStack Shared File System (Manila)
    url: "https://openstack.stfc.ac.uk:8786/v1"
    <<: *defaults_openstack

  - name: OpenStack Shared File System v2 (Manila v2)
    url: "https://openstack.stfc.ac.uk:8786/v2"
    <<: *defaults_openstack

  - name: OpenStack Image (Glance)
    url: "https://openstack.stfc.ac.uk:9292"
    <<: *defaults_openstack

  - name: OpenStack Baremetal (Ironic)
    url: "https://openstack.stfc.ac.uk:6385"
    <<: *defaults_openstack

  - name: OpenStack Baremetal Introspection (Ironic-Inspector)
    url: "https://openstack.stfc.ac.uk:5050/"
    <<: *defaults_openstack

  - name: OpenStack Cloudformation (Heat-CFN)
    url: "https://openstack.stfc.ac.uk:8000/v1"
    <<: *defaults_openstack

  - name: OpenStack Orchestration (Heat)
    url: "https://openstack.stfc.ac.uk:8004/v1"
    <<: *defaults_openstack

  - name: OpenStack Resource Placement
    url: "https://openstack.stfc.ac.uk:8778"
    <<: *defaults_openstack
